# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Notify Slack if failed
        if: ${{ failure() && (github.event_name == 'push' || (github.event_name == 'repository_dispatch' && github.event.action == 'manual-build-publish')) }}
        uses: extenda/actions/slack-message@v0
        with:
          title: 'Build failed for ${{ github.repository }}: ${{ github.workflow }} :heavy_exclamation_mark:'
          text: 'Build failed on ${{ github.event_name }} event. Branch or tag: ${{ github.ref }}. Workflow: ${{ github.workflow }}. Run id: ${{ github.run_id }}'
          fallback: Build failed on ${{ github.event_name }} event.
          service-account-key: ${{ secrets.SECRET_AUTH }}
