# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Notify Slack if failed
      if: ${{ failure() && (github.event_name == 'push' || (github.event_name == 'repository_dispatch' && github.event.action == 'manual-build-publish'))  }}
      uses: extenda/actions/slack-message@v0
      with:
        title: 'Build failed for ${{ github.repository }}: ${{ github.workflow }} :heavy_exclamation_mark:'
        text: 'Build failed on ${{ github.event_name }} event. Branch or tag: ${{ github.ref }}. Workflow: ${{ github.workflow }}. Run id: ${{ github.run_id }}'
        fallback: Build failed on ${{ github.event_name }} event.
        service-account-key: ${{ secrets.SECRET_AUTH }}
